
import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.udry.app',
  appName: 'udry 共享雨傘 ',
  // This is the crucial change: We explicitly tell Capacitor to look for the web assets
  // in the `out` directory, which is generated by the `next build` command
  // when `output: 'export'` is set in next.config.js.
  webDir: 'out',
  android: {
    allowMixedContent: true,
  },
  ios: {
    appendUserAgent: "Firebase/Auth",
    contentInset: "always",
  },
  server: {
    allowNavigation: [
      "identitytoolkit.googleapis.com",
      "udry-app-dev.web.app"
    ]
  },
  plugins: {
    "Capacitor-App": {
      iosScheme: "udry",
      androidScheme: "udry"
    }
  }
};

export default config;
