
// PASTE THIS ENTIRE BLOCK INTO /src/contexts/language-context.tsx

"use client";

import type React from 'react';
import { createContext, useContext, useState, ReactNode, useCallback, useEffect } from 'react';

export type Language = 'en' | 'zh-HK';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  translate: (key: string, replacements?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  'en': {
    // General
    'loading': 'Loading...',
    'cancel_button': 'Cancel',
    'back_button': 'Back',
    'submit_button': 'Submit',
    'save_button': 'Save',
    'edit_button': 'Edit',
    'delete_button': 'Delete',
    'confirm_button': 'Confirm',
    'close_button': 'Close',
    'error_title': 'Error',
    'success_title': 'Success',
    'warning_title': 'Warning',
    'info_title': 'Info',
    'oops_error': 'Oops! Something went wrong.',
    'try_again_button': 'Try Again',
    'go_to_homepage_button': 'Go to Homepage',
    'search_placeholder': 'Search...',
    'not_available_short': 'N/A',

    // Header & Navigation
    'map': 'Map',
    'guide': 'Guide',
    'report_issue': 'Report Issue',
    'login': 'Login',
    'signup': 'Sign Up',
    'logout': 'Logout',
    'add_funds': 'Add Funds',
    'view_balance_history': 'Balance/History',
    'profile_settings': 'Profile Settings',
    'admin_panel_link': 'Admin Panel',
    'language_switcher_label': 'Language',
    'language_english': 'English',
    'language_cantonese': '繁體中文 (Cantonese)',
    'terms_and_conditions_link': 'Terms & Conditions',

    // Auth Pages (Sign In / Sign Up)
    'signin_page_title': 'Sign In - U-Dry',
    'signin_page_description': 'Sign in to your U-Dry account.',
    'signup_page_title': 'Sign Up - U-Dry',
    'signup_page_description': 'Create a new U-Dry account.',
    'welcome_back_title': 'Welcome Back!',
    'signin_form_description': 'Sign in to access your account and manage your U-Dry rentals.',
    'create_account_title': 'Create an Account',
    'signup_form_description': 'Join U-Dry to easily rent and return umbrellas.',
    'email_label': 'Email',
    'email_placeholder': 'your@email.com',
    'password_label': 'Password',
    'password_placeholder': '••••••••',
    'name_label': 'Full Name',
    'name_placeholder': 'John Doe',
    'signin_button': 'Sign In',
    'signup_button': 'Create Account',
    'or_continue_with': 'Or continue with',
    'continue_with_google': 'Continue with Google',
    'continue_with_apple': 'Continue with Apple',
    'dont_have_account_prompt': "Don't have an account?",
    'already_have_account_prompt': 'Already have an account?',
    'auth_error_popup_closed': 'The sign-in process was closed before completion.',
    'auth_error_account_exists': 'An account already exists with this email using a different sign-in method.',
    'auth_success_signin_google': 'Signed in successfully with Google!',
    'auth_success_signin_apple': 'Signed in successfully with Apple!',
    'auth_success_signup_email': 'Account created successfully!',
    'auth_success_signin_email': 'Signed in successfully!',
    'auth_success_signout': 'Signed out successfully.',
    'auth_error_signin_google_failed': 'Google sign-in failed',
    'auth_error_signin_apple_failed': 'Apple sign-in failed',
    'auth_error_signup_email_failed': 'Sign-up failed',
    'auth_error_signin_email_failed': 'Sign-in failed',
    'auth_error_invalid_credential_desc': "The email or password you entered is incorrect. Please check your credentials and try again.",
    'auth_error_signout_failed': 'Sign-out failed',

    // Main Page (Map)
    'find_an_umbrella_title': 'Find Your Umbrella',
    'find_an_umbrella_description': 'Use the map below to find nearby U-Dry umbrella stalls. Click on a stall to see availability and rent an umbrella.',
    'map_config_error_title': 'Map Configuration Error',
    'map_config_error_missing_key': 'The Google Maps API Key is missing, incorrect, or still set to the placeholder.',
    'map_config_error_dev_instructions': 'For local development: Ensure NEXT_PUBLIC_GOOGLE_MAPS_API_KEY is correctly set in your .env.local file.',
    'map_config_error_deploy_instructions': "For deployed/testing links: This key MUST be configured as an environment variable in your hosting provider's settings (e.g., Firebase App Hosting, Vercel, Netlify). .env.local files are NOT used in deployed environments.",
    'map_config_error_key_format': 'The key should look like AIzaSy...',
    'map_config_error_restart_needed': 'After setting the key (locally or in hosting), you must restart your development server or re-deploy for the change to take effect.',
    'map_checking_api_key': 'Checking API Key configuration...',
    'map_loading_config': 'Loading map configuration...',
    'map_locate_me_button': 'Locate Me',
    'map_locate_me_error_generic': 'Geolocation is not supported by your browser.',
    'map_locate_me_error_denied': 'Location permission denied. Please enable it in your browser settings.',
    'map_locate_me_error_unavailable': 'Location information is unavailable.',
    'map_locate_me_error_timeout': 'The request to get user location timed out.',
    'map_locate_me_error_unknown': 'An unknown error occurred while trying to get your location.',
    'map_locate_me_success': 'Map centered on your current location.',
    'map_stall_info_available_umbrellas': 'Available Umbrellas:',
    'map_stall_info_available_slots': 'Available Return Slots:',
    'map_stall_info_rent_button': 'Rent Umbrella',
    'map_stall_info_no_umbrellas_to_rent': 'No umbrellas available to rent at this stall.',
    'map_stall_info_no_slots_to_return': 'No empty slots to return an umbrella.',

    // Rent Page
    'rent_page_title_prefix': 'Rent from',
    'rent_page_title_suffix': '- U-Dry',
    'rent_page_description_prefix': 'Rent an umbrella from',
    'rent_page_description_suffix': '. Check availability and confirm your rental.',
    'rent_stall_not_found_title': 'Stall Not Found - U-Dry',
    'rent_stall_not_found_message': 'The requested umbrella stall could not be found.',
    'rent_back_to_map_button': 'Back to Map',
    'rent_title_prefix': 'Rent from',
    'rent_scan_qr_title': 'Scan QR Code to Unlock',
    'rent_initializing_scanner': 'Initializing scanner...',
    'rent_scanning_qr': 'Scanning for QR code...',
    'rent_scanning_qr_instruction': 'Position the QR code from the rental machine within the frame.',
    'rent_unlocking_umbrella': 'Processing... Unlocking Umbrella!',
    'rent_scanner_error_title': 'Scanner Error',
    'rent_camera_error_title': 'Camera Error',
    'rent_camera_error_desc_generic': "Could not start camera. Check permissions and ensure you're on HTTPS.",
    'rent_camera_permission_denied': 'Camera permission denied. Please enable it to scan QR codes.',
    'rent_camera_not_found': 'No camera found. Please ensure a camera is connected and enabled.',
    'rent_camera_in_use_or_error': 'Camera is already in use or a hardware error occurred.',
    'rent_camera_api_unavailable': 'Camera access is not available in your browser or on this page.',
    'rent_availability_label': 'Availability:',
    'rent_umbrellas_available_text': '{count} / {total} umbrellas available',
    'rent_terms_title': 'Rental Terms:',
    'rent_term_deposit': 'Minimum HK$100 refundable security deposit required on account to rent.',
    'rent_term_free_period': 'First rental is free!',
    'rent_term_hourly_rate': 'After first rental: HK$5 per hour.',
    'rent_term_daily_cap': 'Daily charge capped at HK$25 (for each 24-hour period).',
    'rent_term_return_anywhere': 'Return to any U-Dry stall.',
    'rent_term_forfeit_deposit': "A HK$100 penalty (equal to the deposit) will be charged to your balance if not returned within 72 hours.",
    'rent_unlock_success_toast_title': 'Umbrella Unlocked!',
    'rent_unlock_success_toast_desc': 'Your rental from {stallName} has started. (QR Scan Simulated)',
    'rent_error_no_umbrellas_toast_title': 'No Umbrellas Available',
    'rent_error_no_umbrellas_toast_desc': 'Sorry, there are no umbrellas available at this stall.',
    'rent_error_active_rental_toast_title': 'Rental In Progress',
    'rent_error_active_rental_toast_desc': 'You already have an active rental. Please end it before starting a new one.',
    'rent_error_auth_required_title': 'Authentication Required',
    'rent_error_auth_required_desc': 'You must be logged in to rent an umbrella.',
    'rent_signin_to_rent_button': 'Sign In to Rent',
    'rent_loading_account_status': 'Loading account status...',
    'rent_active_rental_message': 'You have an active rental. Please end it first. Camera scan disabled.',
    'rent_no_umbrellas_message': 'No umbrellas available at this stall. Camera scan disabled.',

    // Return Page
    'return_page_title': 'Return Umbrella - U-Dry',
    'return_page_description': 'Scan a QR code to return your rented umbrella.',
    'return_back_to_map_button': 'Back to Map / Cancel Return',
    'return_title': 'Return Umbrella',
    'return_stall_label_prefix': 'Returning umbrella from:',
    'return_time_elapsed_label': 'Time Elapsed:',
    'return_scan_qr_title': 'Scan Stall QR Code to Confirm Return',
    'return_initializing_scanner': 'Initializing scanner...',
    'return_scanning_qr': 'Scanning for QR code...',
    'return_scanning_qr_instruction': 'Position the QR code from the rental machine within the frame.',
    'return_processing_return': 'Processing Return...',
    'return_scanner_error_title': 'Scanner Error',
    'return_camera_error_title': 'Camera Error',
    'return_camera_error_desc_generic': "Could not start camera. Check permissions and ensure you're on HTTPS.",
    'return_camera_permission_denied': 'Camera permission denied. Please enable it to scan QR codes.',
    'return_camera_not_found': 'No camera found. Please ensure a camera is connected and enabled.',
    'return_camera_in_use_or_error': 'Camera is already in use or a hardware error occurred.',
    'return_camera_api_unavailable': 'Camera access is not available in your browser or on this page.',
    'return_button_processing': 'Processing Return...',
    'return_loading_details': 'Loading rental details...',
    'return_no_active_rental_toast_title': 'No Active Rental',
    'return_no_active_rental_toast_desc': 'You do not have an active rental to return.',
    'return_success_toast_title': 'Umbrella Return Confirmed!',
    'return_success_toast_desc': 'Your umbrella rental from {stallName} has been successfully returned. (QR Scan Simulated)',

    // Rental Timer
    'rental_timer_loading_status': 'Loading rental status...',
    'rental_timer_active_rental_title': 'Active Rental',
    'rental_timer_stall_label': 'Stall:',
    'rental_timer_charge_prefix': 'HK$',
    'rental_timer_daily_cap_message': 'Daily charge capped for this 24hr period.',
    'rental_timer_warning_36h': 'Warning: Max rental is 72 hours. After this, a HK$100 penalty will be charged to your balance. To appeal, call {customerServiceNumber}.',
    'rental_timer_warning_72h': 'Rental exceeded 72 hours. A HK$100 penalty has been charged to your balance. Please return the umbrella.',
    'rental_timer_contact_for_appeal': 'Call: {customerServiceNumber}',
    'rental_timer_return_button': 'Return Umbrella',
    'rental_timer_return_overdue_button': 'Return Overdue Umbrella',

    // Guide Page
    'guide_page_title': 'User Guide - U-Dry',
    'guide_page_description': 'Learn how to use the U-Dry service, from finding stalls to renting and returning umbrellas.',
    'guide_welcome_title': 'Welcome to the U-Dry Guide!',
    'guide_welcome_description': "Here's a simple guide to help you get started with renting and returning umbrellas.",
    'guide_step_1_title': '1. Find a Stall',
    'guide_step_1_description': "Use the interactive map on our homepage to locate the nearest U-Dry umbrella stall. You can see how many umbrellas are available at each location.",
    'guide_step_2_title': '2. Rent an Umbrella',
    'guide_step_2_description': "At the stall, select 'Rent Umbrella' on the machine or in the app. Scan the QR code on the machine using your phone's camera through our app to unlock an umbrella. Make sure you have enough balance in your account (min. HK$100).",
    'guide_step_3_title': '3. Enjoy Your Rental',
    'guide_step_3_description': "Use the umbrella for as long as you need. It's HK$5 per hour, capped at HK$25 per 24-hour period. Remember to return it within 3 days (72 hours) to avoid forfeiting your deposit.",
    'guide_step_4_title': '4. Return the Umbrella',
    'guide_step_4_description': "You can return the umbrella to ANY U-Dry stall that has an available slot. In the app, select 'Return Umbrella' and scan the QR code on the return slot of the machine. Ensure the umbrella is securely placed.",
    'guide_faq_title': 'Frequently Asked Questions',
    'faq_q1_trigger': 'What if there are no umbrellas at a stall?',
    'faq_q1_content': 'The map shows real-time availability. If a stall is empty, please look for another nearby stall. We are constantly working to ensure umbrellas are well-distributed.',
    'faq_q2_trigger': 'How do I add funds to my account?',
    'faq_q2_content': "You can add funds through the 'Add Funds' or 'Deposit' section in the app using various payment methods. A minimum balance of HK$100 is required to initiate a rental.",
    'faq_q3_trigger': 'What happens if I lose or damage an umbrella?',
    'faq_q3_content': "Please report any lost or damaged umbrellas immediately through the 'Report Issue' feature in the app. For lost umbrellas, your HK$100 deposit may be forfeited. For damaged umbrellas, we will assess the situation. Honest reporting is appreciated!",
    'faq_q4_trigger': 'Can I reserve an umbrella?',
    'faq_q4_content': 'Currently, we do not offer reservations. Umbrellas are available on a first-come, first-served basis to ensure fairness.',
    'guide_need_help_title': 'Need More Help?',
    'guide_need_help_description': "If you have any other questions or face issues, please use the 'Report Issue' feature in the app or contact our customer support.",
 
    // Deposit Page
    'deposit_page_title': 'Add Funds - U-Dry',
    'deposit_page_description': 'Add funds to your U-Dry account to rent umbrellas.',
    'deposit_loading_account': 'Loading account details...',
    'access_denied': 'Access Denied',
    'deposit_login_required': 'You need to be logged in to add funds to your account.',
    'deposit_title_one_time': 'Pay One-Time Security Deposit',
    'deposit_desc_one_time': 'A HK$100 refundable deposit is required to start renting umbrellas.',
    'deposit_alert_title': 'One-Time Deposit',
    'deposit_alert_desc': 'This is a refundable security deposit. It cannot be used for rental fees. You can request a refund of your deposit at any time, provided you have no active rentals.',
    'deposit_amount_label_fixed': 'Deposit Amount',
    'deposit_payment_method_label': 'Select Payment Method',
    'deposit_selected_method_note': 'You selected:',
    'deposit_proceed_button': 'Pay HK$100 Deposit',
    'add_balance_title': 'Add Balance',
    'add_balance_desc': 'Top up your spendable balance. This will be used to pay for rentals.',
    'add_balance_amount_label': 'Select an amount to add (HK$)',
    'add_balance_custom_amount': 'Custom',
    'add_balance_enter_custom_amount': 'Enter custom amount',
    'add_balance_proceed_button': 'Add to Balance',

    'payment_method_credit_card': 'Credit/Debit Card',
    'payment_method_apple_pay': 'Apple Pay',
    'payment_method_payme': 'PayMe',
    'payment_method_google_pay': 'Google Pay',
    'payment_method_fps': 'FPS (轉數快)',
    'payment_method_alipay': 'AlipayHK',
    'payment_method_alipay_cn': 'Alipay (CN)',
    'payment_method_wechat_pay': 'WeChat Pay HK',
    'deposit_simulation_alert_title': 'Payment Simulation',
    'deposit_simulation_alert_message': "This is a simulated payment. You selected {methodName} for HK${amount}. In a real app, you'd be redirected. For testing, you can visit the payment provider's sandbox/test page if available: {testUrl}",

    // Account Balance Page
    'balance_page_title': 'Account Balance - U-Dry',
    'balance_page_description': 'View your account balance and transaction history for U-Dry.',
    'balance_loading_details': 'Loading account details...',
    'balance_login_required': 'You need to be logged in to view your account balance.',
    'balance_title': 'Account Wallet',
    'balance_description': 'Manage your deposit and spendable balance.',
    'balance_spendable_balance_label': 'Spendable Balance',
    'balance_spendable_balance_desc': 'Used to pay for rental fees.',
    'balance_deposit_label': 'Security Deposit',
    'balance_deposit_desc': 'Refundable. Required to rent.',
    'balance_transaction_history_label': 'Transaction History',
    'balance_transaction_history_placeholder': 'Your transaction history will appear here once the feature is live.',
    'balance_rental_terms_note': 'First rental is free! Then HK$5/hr, capped at HK$25/day. Deposit forfeited after 72 hrs.',
    'add_balance_button': 'Add Balance',
    'pay_deposit_button': 'Pay Deposit',


    // Report Issue Dialog
    'report_issue_dialog_title': 'Report an Issue',
    'report_issue_dialog_select_description': 'Please select the type of issue you are experiencing.',
    'report_issue_lost_stolen_button': 'Lost or Stolen Umbrella',
    'report_issue_lost_stolen_description': 'Report if the umbrella you rented is lost or has been stolen.',
    'report_issue_broken_button': 'Broken/Damaged Umbrella or Stall',
    'report_issue_broken_description': "Report a faulty umbrella or a malfunctioning stall.",
    'report_issue_contact_support_button': 'Other / Contact Support',
    'report_issue_contact_support_description': 'For any other issues, or if you need to speak to someone.',
    'report_issue_toast_auth_required_title': 'Login Required',
    'report_issue_toast_auth_required_desc': "Please sign in to report this type of issue.",
    'report_issue_toast_no_active_rental_title': 'No Active Rental',
    'report_issue_toast_no_active_rental_desc': 'This option is for reporting issues with an umbrella you are currently renting. You do not have an active rental.',
    'report_issue_confirm_lost_stolen_title': 'Confirm Lost/Stolen Report',
    'report_issue_back_to_selection_button': 'Back to Selection',
    'report_issue_important_notice_title': 'Important Notice',
    'report_issue_confirm_lost_stolen_alert_desc': "Reporting an umbrella as lost or stolen will end your current rental. Your HK$100 deposit may be forfeited. This action cannot be undone through the app. Please ensure the umbrella is genuinely lost or stolen. If you find it later, contact support.",
    'report_issue_current_rental_label': 'Current Rental:',
    'report_issue_started_label': 'Started:',
    'report_issue_yes_report_lost_stolen_button': 'Yes, Report Lost/Stolen',
    'report_issue_toast_lost_stolen_title': 'Lost/Stolen Umbrella Reported',
    'report_issue_toast_lost_stolen_desc': 'Your rental has been ended. We have logged this issue. Your deposit may be forfeited. Please contact support if you have questions.',
    'report_issue_capture_media_title': 'Report Broken Item',
    'report_issue_capture_media_desc': 'Please point your camera at the broken umbrella or stall. This helps us identify and fix the issue faster. (This is a simulation - no actual photo is taken or stored).',
    'report_issue_initializing_camera': 'Initializing camera...',
    'report_issue_camera_error_title': 'Camera Error',
    'report_issue_camera_error_desc_generic': 'Could not access the camera. Please check permissions.',
    'report_issue_retry_camera_button': 'Retry Camera',
    'report_issue_confirm_report_button': 'Confirm Report',
    'report_issue_toast_multiple_broken_title': 'Multiple Broken Reports Today',
    'report_issue_toast_multiple_broken_desc': 'Thank you for your report. We see you have submitted {count} reports for broken items today. Your current rental (if any) has been ended. If this is unusual or you need further assistance, please contact customer service at {customerServiceNumber}.',
    'report_issue_toast_broken_rented_title': 'Broken Rented Umbrella Reported',
    'report_issue_toast_broken_rented_desc': 'Thank you. Your rental has been ended, and the issue logged. We appreciate your help in keeping our service running smoothly!',
    'report_issue_toast_report_submitted_title': 'Report Submitted',
    'report_issue_toast_report_submitted_desc': 'Thank you for your report! We will look into this issue.',
    'report_issue_camera_permission_denied': 'Camera permission denied. Please enable camera access in your browser settings to report a broken item with media.',
    'report_issue_camera_not_found': 'No camera found. Please ensure a camera is connected and enabled.',
    'report_issue_camera_in_use_or_error': 'Camera is already in use by another application or a hardware error occurred.',
    'report_issue_camera_api_unavailable': 'Camera access is not available in your browser or on this page (e.g. not HTTPS).',
    'report_issue_contact_support_step_title': 'Contact Customer Support',
    'report_issue_need_assistance_title': 'Need Assistance?',
    'report_issue_need_assistance_desc': 'For urgent matters or issues not covered, please contact our customer support.',
    'report_issue_contact_info_text': 'You can reach us by phone at <strong class="text-primary">{customerServiceNumber}</strong>.',
    'report_issue_call_customer_service_button': 'Call Customer Service',

    // Admin Page
    'admin_page_title': 'Admin Panel - U-Dry',
    'admin_page_description': 'Manage U-Dry stalls and operations.',
    'admin_verifying_access': '正在驗證權限...',
    'admin_access_denied_title': '權限不足',
    'admin_access_denied_desc': '您沒有權限瀏覽此頁面。此區域僅限管理員存取。',
    'admin_go_to_homepage_button': '前往主頁',
    'admin_panel_main_title': 'U-Dry 管理員面板',
    'admin_welcome_message': '歡迎，{userName}。管理您的 U-Dry 營運。',
    'admin_dashboard_overview_title': '儀表板概覽',
    'admin_dashboard_overview_desc': '快速查看營運數據及分析。',
    'admin_stat_total_stalls': '總租借站數量',
    'admin_stat_total_stalls_desc': '目前運作中',
    'admin_stat_total_umbrellas': '總雨傘數量',
    'admin_stat_total_umbrellas_desc': '所有租借站合計',
    'admin_stat_issues_reported': '已報告問題',
    'admin_stat_issues_reported_desc': '完整追蹤為未來功能',
    'admin_stat_avg_weekly_transactions': '平均每週交易數 / 租借站',
    'admin_stat_avg_weekly_transactions_desc': '基準平均值 (預留位置)',
    'admin_stat_avg_weekly_revenue': '平均每週收入 / 租借站',
    'admin_stat_avg_weekly_revenue_desc': '基準平均值 (預留位置)',
    'admin_stat_total_active_rentals': '目前進行中租賃總數',
    'admin_stat_active_rentals_desc': '即時進行中的租借數量',
    'admin_stat_analytics_desc': '整合資料庫後將啟用分析功能',
    'admin_stat_total_borrowing': '總借出次數',
    'admin_stat_total_borrowing_desc': '自追蹤開始',
    'admin_stat_total_returns': '總歸還次數',
    'admin_stat_total_returns_desc': '自追蹤開始',
    'admin_stall_management_title': '租借站管理',
    'admin_stall_management_desc': '檢視、管理和控制各個雨傘租借站。',
    'admin_stall_availability_label': '可用數量：',
    'admin_stall_transactions_label': '交易數 (本週)：',
    'admin_stall_revenue_label': '收入 (本週)：',
    'admin_stall_edit_button': '編輯詳情',
    'admin_stall_unlock_button': '解鎖',
    'admin_stall_manage_features_soon': '更多租借站管理功能即將推出。',
    'admin_machine_reg_title': '機器註冊',
    'admin_machine_reg_desc': '將新的雨傘機加入系統。(預留位置)',
    'admin_machine_reg_placeholder_text': '新增機器、指定其 ID、位置和初始雨傘數量的介面將在此處。',
    'admin_machine_reg_add_button': '新增機器',
    'admin_stall_available_umbrellas_label': '可用雨傘數量:',
    
    // Profile Settings Page
    'profile_settings_page_title': '個人設定 - U-Dry',
    'profile_settings_page_description': '查看並更新您的個人資料。',
    'profile_settings_title': '個人設定',
    'profile_settings_description': '管理您的帳戶詳細資料和偏好設定。',
    'profile_settings_name_label': '名稱',
    'profile_settings_email_label': '電子郵件',
    'profile_settings_update_button': '更新個人資料',
    'profile_settings_update_success': '個人資料更新成功！',
    'profile_settings_update_error': '個人資料更新失敗。',
    'profile_settings_loading': '正在載入個人資料...',
    'profile_settings_login_required': '您需要登入才能查看個人設定。',
    
    // Change Password Section (within Profile Settings)
    'change_password_title': '更改密碼',
    'change_password_description': '更新您的帳戶密碼。',
    'current_password_label': '目前密碼',
    'new_password_label': '新密碼',
    'confirm_new_password_label': '確認新密碼',
    'profile_settings_change_password_button': '更改密碼',
    'toast_password_change_success_title': '密碼已更改',
    'toast_password_change_success_desc': '您的密碼已成功更新。',
    'toast_password_change_error_title': '更改密碼失敗',
    'toast_password_change_error_desc': '無法更改密碼。請確保您目前的密碼正確無誤，然後再試一次。',
    'toast_password_mismatch': "新密碼不符。",
    'toast_reauth_required': "為安全起見，請先重新登入再更改密碼。",
    
    // Terms and Conditions Page
    'terms_page_title': '服務條款 - U-Dry',
    'terms_page_description': '閱讀使用 U-Dry 服務的服務條款。',
    'terms_content_title': '服務條款',
    'terms_last_updated': '最後更新日期：',
    'terms_section_1_title': '引言',
    'terms_section_1_content': "歡迎使用 U-Dry！本服務條款概述了使用 U-Dry 應用程式和服務的規則和規定。存取此應用程式即表示您接受這些條款和條件。如果您不同意本頁面所述的所有條款和條件，請勿繼續使用 U-Dry。",
    'terms_section_2_title': '免責聲明及責任限制',
    'terms_section_2_content_p1': "U-Dry 應用程式及其服務均以「現狀」和「現有」的基礎提供，不附帶任何明示或暗示的保證。我們不保證服務不會中斷、及時、安全或無錯誤。",
    'terms_section_2_content_p2': "在適用法律允許的最大範圍內，U-Dry 不對任何間接、附帶、特殊、後果性或懲罰性損害，或任何利潤或收入損失（無論是直接或間接產生），或任何數據、使用、商譽或其他無形損失負責，該等損失源於 (a) 您存取或使用或無法存取或使用本服務；(b) 任何第三方在本服務上的任何行為或內容；(c) 從本服務獲得的任何內容；及 (d) 未經授權存取、使用或更改您的傳輸或內容。這包括但不限於因使用本應用程式或其服務而據稱遭受的任何身體、精神或金錢損失。",
    'terms_section_3_title': '數據使用和隱私',
    'terms_section_3_content': "使用 U-Dry 即表示您同意我們根據我們的隱私政策（將添加連結）收集和使用資訊。我們可能會收集與您使用本應用程式和服務相關的數據，例如租賃歷史、位置數據（經您同意）和設備資訊。這些數據可能用於改進我們的服務、提供客戶支援以及進行分析。我們致力於保護您的隱私並負責任地處理您的數據。",
    'terms_section_4_title': '用戶責任',
    'terms_section_4_content': "您有責任維護您的帳戶和密碼的機密性，並限制對您設備的存取。您同意對在您的帳戶或密碼下發生的所有活動承擔責任。您有責任按時歸還租借的雨傘，並根據應用程式的指引報告任何損壞或遺失。濫用服務或雨傘可能導致帳戶暫停或終止，以及從您的可用餘額中扣除等同於按金的罰款。",
    'terms_section_5_title': '管轄法律',
    'terms_section_5_content': "本條款應受香港特別行政區法律管轄並依其解釋，不考慮其法律衝突規定。",
    'terms_section_6_title': '條款變更',
    'terms_section_6_content': "我們保留自行決定隨時修改或替換這些條款的權利。如果修訂是重大的，我們將在任何新條款生效前至少提前30天發出通知。何為重大變更將由我們自行決定。在任何修訂生效後繼續存取或使用我們的服務，即表示您同意受修訂條款的約束。",
  },
  'zh-HK': {
    // General
    'loading': '載入中...',
    'cancel_button': '取消',
    'back_button': '返回',
    'submit_button': '提交',
    'save_button': '儲存',
    'edit_button': '編輯',
    'delete_button': '刪除',
    'confirm_button': '確認',
    'close_button': '關閉',
    'error_title': '錯誤',
    'success_title': '成功',
    'warning_title': '警告',
    'info_title': '資訊',
    'oops_error': '哎呀！出現問題。',
    'try_again_button': '再試一次',
    'go_to_homepage_button': '返回主頁',
    'search_placeholder': '搜尋...',
    'not_available_short': '不適用',

    // Header & Navigation
    'map': '地圖',
    'guide': '指南',
    'report_issue': '報告問題',
    'login': '登入',
    'signup': '註冊',
    'logout': '登出',
    'add_funds': '增值',
    'view_balance_history': '餘額/紀錄',
    'profile_settings': '個人設定',
    'admin_panel_link': '管理員面板',
    'language_switcher_label': '語言',
    'language_english': 'English',
    'language_cantonese': '繁體中文',
    'terms_and_conditions_link': '服務條款',

    // Auth Pages (Sign In / Sign Up)
    'signin_page_title': '登入 - U-Dry',
    'signin_page_description': '登入您的 U-Dry 帳戶。',
    'signup_page_title': '註冊 - U-Dry',
    'signup_page_description': '建立一個新的 U-Dry 帳戶。',
    'welcome_back_title': '歡迎回來！',
    'signin_form_description': '登入以存取您的帳戶並管理您的 U-Dry 租借。',
    'create_account_title': '建立帳戶',
    'signup_form_description': '加入 U-Dry，輕鬆租借和歸還雨傘。',
    'email_label': '電子郵件',
    'email_placeholder': 'your@email.com',
    'password_label': '密碼',
    'password_placeholder': '••••••••',
    'name_label': '全名',
    'name_placeholder': '陳大文',
    'signin_button': '登入',
    'signup_button': '建立帳戶',
    'or_continue_with': '或使用其他方式繼續',
    'continue_with_google': '使用 Google 繼續',
    'continue_with_apple': '使用 Apple 繼續',
    'dont_have_account_prompt': '還沒有帳戶？',
    'already_have_account_prompt': '已經有帳戶了？',
    'auth_error_popup_closed': '登入過程在完成前已關閉。',
    'auth_error_account_exists': '此電子郵件已使用不同的登入方式註冊帳戶。',
    'auth_success_signin_google': '已成功使用 Google 登入！',
    'auth_success_signin_apple': '已成功使用 Apple 登入！',
    'auth_success_signup_email': '帳戶建立成功！',
    'auth_success_signin_email': '登入成功！',
    'auth_success_signout': '登出成功。',
    'auth_error_signin_google_failed': 'Google 登入失敗',
    'auth_error_signin_apple_failed': 'Apple 登入失敗',
    'auth_error_signup_email_failed': '註冊失敗',
    'auth_error_signin_email_failed': '登入失敗',
    'auth_error_invalid_credential_desc': '您輸入的電子郵件或密碼不正確。請檢查您的憑證後再試一次。',
    'auth_error_signout_failed': '登出失敗',

    // Main Page (Map)
    'find_an_umbrella_title': '尋找您的雨傘',
    'find_an_umbrella_description': '使用下面的地圖尋找附近的 U-Dry 雨傘租借站。點擊租借站以查看可用數量並租借雨傘。',
    'map_config_error_title': '地圖設定錯誤',
    'map_config_error_missing_key': 'Google Maps API 金鑰遺失、不正確或仍設定為預留位置。',
    'map_config_error_dev_instructions': '本地開發：請確保您的 .env.local 檔案中已正確設定 NEXT_PUBLIC_GOOGLE_MAPS_API_KEY。',
    'map_config_error_deploy_instructions': '已部署/測試連結：此金鑰必須在您的託管服務提供商（例如 Firebase App Hosting、Vercel、Netlify）的設定中設定為環境變數。.env.local 檔案不會在已部署的環境中使用。',
    'map_config_error_key_format': '金鑰應類似於 AIzaSy...',
    'map_config_error_restart_needed': '設定金鑰後（無論是本地還是託管服務），您必須重新啟動開發伺服器或重新部署，變更才會生效。',
    'map_checking_api_key': '正在檢查 API 金鑰設定...',
    'map_loading_config': '正在載入地圖設定...',
    'map_locate_me_button': '我的位置',
    'map_locate_me_error_generic': '您的瀏覽器不支援地理位置定位。',
    'map_locate_me_error_denied': '地理位置權限遭拒。請在您的瀏覽器設定中啟用它。',
    'map_locate_me_error_unavailable': '無法取得地理位置資訊。',
    'map_locate_me_error_timeout': '取得使用者位置的請求已逾時。',
    'map_locate_me_error_unknown': '嘗試取得您的位置時發生未知錯誤。',
    'map_locate_me_success': '地圖已置中於您目前的位置。',
    'map_stall_info_available_umbrellas': '可用雨傘數量：',
    'map_stall_info_available_slots': '可用歸還空位：',
    'map_stall_info_rent_button': '租借雨傘',
    'map_stall_info_no_umbrellas_to_rent': '此租借站目前沒有可用的雨傘。',
    'map_stall_info_no_slots_to_return': '此租借站目前沒有空的歸還位置。',
    
    // Rent Page
    'rent_page_title_prefix': '從',
    'rent_page_title_suffix': '租借 - U-Dry',
    'rent_page_description_prefix': '從',
    'rent_page_description_suffix': '租借雨傘。查看可用性並確認您的租借。',
    'rent_stall_not_found_title': '找不到租借站 - U-Dry',
    'rent_stall_not_found_message': '找不到您請求的雨傘租借站。',
    'rent_back_to_map_button': '返回地圖',
    'rent_title_prefix': '從',
    'rent_scan_qr_title': '掃描 QR 碼解鎖',
    'rent_initializing_scanner': '正在啟動掃描器...',
    'rent_scanning_qr': '正在掃描 QR 碼...',
    'rent_scanning_qr_instruction': '請將租借機上的 QR 碼對準畫面中的方框。',
    'rent_unlocking_umbrella': '處理中...正在解鎖雨傘！',
    'rent_scanner_error_title': '掃描器錯誤',
    'rent_camera_error_title': '相機錯誤',
    'rent_camera_error_desc_generic': '無法啟動相機。請檢查權限並確保您正在使用 HTTPS。',
    'rent_camera_permission_denied': '相機權限遭拒。請啟用權限以掃描 QR 碼。',
    'rent_camera_not_found': '找不到相機。請確保相機已連接並啟用。',
    'rent_camera_in_use_or_error': '相機已被其他應用程式使用或發生硬體錯誤。',
    'rent_camera_api_unavailable': '您的瀏覽器或此頁面無法存取相機。',
    'rent_availability_label': '可用數量：',
    'rent_umbrellas_available_text': '{count} / {total} 把可用雨傘',
    'rent_terms_title': '租借條款：',
    'rent_term_deposit': '租借需帳戶內至少有 HK$100 可退還的按金。',
    'rent_term_free_period': '首次租借免費！',
    'rent_term_hourly_rate': '首次租借後：每小時 HK$5。',
    'rent_term_daily_cap': '每日收費上限為 HK$25（每 24 小時）。',
    'rent_term_return_anywhere': '可歸還至任何 U-Dry 租借站。',
    'rent_term_forfeit_deposit': "若 72 小時內未歸還雨傘，將會從您的帳戶餘額中扣除 HK$100 的罰款（等同按金金額）。",
    'rent_unlock_success_toast_title': '雨傘已解鎖！',
    'rent_unlock_success_toast_desc': '您從 {stallName} 的租借已開始。（QR 碼掃描模擬）',
    'rent_error_no_umbrellas_toast_title': '沒有可用雨傘',
    'rent_error_no_umbrellas_toast_desc': '抱歉，此租借站目前沒有可用的雨傘。',
    'rent_error_active_rental_toast_title': '租借進行中',
    'rent_error_active_rental_toast_desc': '您已有一個進行中的租借。請先結束該租借再開始新的。',
    'rent_error_auth_required_title': '需要驗證身份',
    'rent_error_auth_required_desc': '您必須登入才能租借雨傘。',
    'rent_signin_to_rent_button': '登入以租借',
    'rent_loading_account_status': '正在載入帳戶狀態...',
    'rent_active_rental_message': '您已有一個進行中的租借。請先結束它。相機掃描已停用。',
    'rent_no_umbrellas_message': '此租借站沒有可用雨傘。相機掃描已停用。',
    
    // Return Page
    'return_page_title': '歸還雨傘 - U-Dry',
    'return_page_description': '掃描 QR 碼以歸還您租借的雨傘。',
    'return_back_to_map_button': '返回地圖 / 取消歸還',
    'return_title': '歸還雨傘',
    'return_stall_label_prefix': '歸還從：',
    'return_time_elapsed_label': '已用時間：',
    'return_scan_qr_title': '掃描租借站 QR 碼以確認歸還',
    'return_initializing_scanner': '正在啟動掃描器...',
    'return_scanning_qr': '正在掃描 QR 碼...',
    'return_scanning_qr_instruction': '請將租借機上的 QR 碼對準畫面中的方框。',
    'return_processing_return': '正在處理歸還...',
    'return_scanner_error_title': '掃描器錯誤',
    'return_camera_error_title': '相機錯誤',
    'return_camera_error_desc_generic': '無法啟動相機。請檢查權限並確保您正在使用 HTTPS。',
    'return_camera_permission_denied': '相機權限遭拒。請啟用權限以掃描 QR 碼。',
    'return_camera_not_found': '找不到相機。請確保相機已連接並啟用。',
    'return_camera_in_use_or_error': '相機已被其他應用程式使用或發生硬體錯誤。',
    'return_camera_api_unavailable': '您的瀏覽器或此頁面無法存取相機。',
    'return_button_processing': '處理歸還中...',
    'return_loading_details': '正在載入租借詳情...',
    'return_no_active_rental_toast_title': '沒有進行中的租借',
    'return_no_active_rental_toast_desc': '您沒有進行中的租借可以歸還。',
    'return_success_toast_title': '雨傘歸還已確認！',
    'return_success_toast_desc': '您從 {stallName} 的租借已成功歸還。（QR 碼掃描模擬）',

    // Rental Timer
    'rental_timer_loading_status': '正在載入租借狀態...',
    'rental_timer_active_rental_title': '進行中的租借',
    'rental_timer_stall_label': '租借站：',
    'rental_timer_charge_prefix': 'HK$',
    'rental_timer_daily_cap_message': '此 24 小時內的費用已達每日上限。',
    'rental_timer_warning_36h': '警告：最長租借時間為 72 小時。超過後，將會從您的餘額中扣除 HK$100 的罰款。如需申訴，請致電 {customerServiceNumber}。',
    'rental_timer_warning_72h': '租借已超過 72 小時。已從您的餘額中扣除 HK$100 的罰款。請歸還雨傘。',
    'rental_timer_contact_for_appeal': '致電：{customerServiceNumber}',
    'rental_timer_return_button': '歸還雨傘',
    'rental_timer_return_overdue_button': '歸還逾期雨傘',

    // Guide Page
    'guide_page_title': '用戶指南 - U-Dry',
    'guide_page_description': '了解如何使用 U-Dry 服務，從尋找租借站到租借和歸還雨傘。',
    'guide_welcome_title': '歡迎來到 U-Dry 指南！',
    'guide_welcome_description': '這是一個簡單的指南，幫助您開始租借和歸還雨傘。',
    'guide_step_1_title': '1. 尋找租借站',
    'guide_step_1_description': '使用我們主頁上的互動地圖，尋找最近的 U-Dry 雨傘租借站。您可以查看每個地點有多少把可用的雨傘。',
    'guide_step_2_title': '2. 租借雨傘',
    'guide_step_2_description': '在租借站，於機器上或在應用程式中選擇「租借雨傘」。透過我們的應用程式使用手機相機掃描機器上的 QR 碼以解鎖雨傘。請確保您的帳戶有足夠的餘額（最低 HK$100）。',
    'guide_step_3_title': '3. 享受您的租借',
    'guide_step_3_description': "您可以隨心所欲地使用雨傘。每小時收費 HK$5，每 24 小時上限為 HK$25。請記得在 3 天（72 小時）內歸還，以免被沒收按金。",
    'guide_step_4_title': '4. 歸還雨傘',
    'guide_step_4_description': '您可以將雨傘歸還至任何有空位的 U-Dry 租借站。在應用程式中，選擇「歸還雨傘」並掃描機器歸還槽上的 QR 碼。請確保雨傘已穩固放置。',
    'guide_faq_title': '常見問題',
    'faq_q1_trigger': '如果租借站沒有雨傘怎麼辦？',
    'faq_q1_content': '地圖會顯示即時的可用數量。如果一個租借站是空的，請尋找附近的其他租借站。我們正不斷努力確保雨傘分佈均勻。',
    'faq_q2_trigger': '如何為我的帳戶增值？',
    'faq_q2_content': '您可以透過應用程式中的「增值」或「按金」部分，使用多種付款方式增值。開始租借需要最低 HK$100 的餘額。',
    'faq_q3_trigger': '如果我遺失或損壞了雨傘怎麼辦？',
    'faq_q3_content': '請立即透過應用程式中的「報告問題」功能報告任何遺失或損壞的雨傘。對於遺失的雨傘，您的 HK$100 按金可能會被沒收。對於損壞的雨傘，我們將評估情況。感謝您的誠實報告！',
    'faq_q4_trigger': '我可以預約雨傘嗎？',
    'faq_q4_content': '目前，我們不提供預約服務。雨傘以先到先得的方式提供，以確保公平。',
    'guide_need_help_title': '需要更多幫助？',
    'guide_need_help_description': '如果您有任何其他問題或遇到困難，請使用應用程式中的「報告問題」功能或聯絡我們的客戶支援。',
 
    // Deposit Page
    'deposit_page_title': '增值 - U-Dry',
    'deposit_page_description': '為您的 U-Dry 帳戶增值以租借雨傘。',
    'deposit_loading_account': '正在載入帳戶詳情...',
    'access_denied': '存取被拒',
    'deposit_login_required': '您需要登入才能為您的帳戶增值。',
    'deposit_title_one_time': '支付一次性按金',
    'deposit_desc_one_time': '租借雨傘需要支付 HK$100 的可退還按金。',
    'deposit_alert_title': '一次性按金',
    'deposit_alert_desc': '這是可退還的按金，不能用於支付租借費用。只要您沒有進行中的租借，您可以隨時申請退還按金。',
    'deposit_amount_label_fixed': '按金金額',
    'deposit_payment_method_label': '選擇付款方式',
    'deposit_selected_method_note': '您已選擇：',
    'deposit_proceed_button': '支付 HK$100 按金',
    'add_balance_title': '增值餘額',
    'add_balance_desc': '為您的可用餘額增值。此餘額將用於支付租借費用。',
    'add_balance_amount_label': '選擇增值金額 (HK$)',
    'add_balance_custom_amount': '自訂',
    'add_balance_enter_custom_amount': '輸入自訂金額',
    'add_balance_proceed_button': '增值到餘額',

    'payment_method_credit_card': '信用卡/扣帳卡',
    'payment_method_apple_pay': 'Apple Pay',
    'payment_method_payme': 'PayMe',
    'payment_method_google_pay': 'Google Pay',
    'payment_method_fps': '轉數快 (FPS)',
    'payment_method_alipay': '支付寶香港 (AlipayHK)',
    'payment_method_alipay_cn': '支付寶 (Alipay CN)',
    'payment_method_wechat_pay': '微信支付香港 (WeChat Pay HK)',
    'deposit_simulation_alert_title': '付款模擬',
    'deposit_simulation_alert_message': '這是一個模擬付款。您選擇了 {methodName} 支付 HK${amount}。在真實的應用程式中，您會被重新導向。若要測試，您可以瀏覽付款供應商的沙盒/測試頁面（如果有的話）：{testUrl}',

    // Account Balance Page
    'balance_page_title': '帳戶餘額 - U-Dry',
    'balance_page_description': '查看您的 U-Dry 帳戶餘額和交易紀錄。',
    'balance_loading_details': '正在載入帳戶詳情...',
    'balance_login_required': '您需要登入才能查看您的帳戶餘額。',
    'balance_title': '帳戶錢包',
    'balance_description': '管理您的按金和可用餘額。',
    'balance_spendable_balance_label': '可用餘額',
    'balance_spendable_balance_desc': '用於支付租借費用。',
    'balance_deposit_label': '按金',
    'balance_deposit_desc': '可退還。租借必需。',
    'balance_transaction_history_label': '交易紀錄',
    'balance_transaction_history_placeholder': '此功能上線後，您的交易紀錄將會顯示在這裡。',
    'balance_rental_terms_note': '首次租借免費！其後每小時 HK$5，每日上限 HK$25。超過 72 小時未歸還將沒收按金。',
    'add_balance_button': '增值餘額',
    'pay_deposit_button': '支付按金',


    // Report Issue Dialog
    'report_issue_dialog_title': '報告問題',
    'report_issue_dialog_select_description': '請選擇您遇到的問題類型。',
    'report_issue_lost_stolen_button': '雨傘遺失或被盜',
    'report_issue_lost_stolen_description': '報告您租借的雨傘已遺失或被盜。',
    'report_issue_broken_button': '雨傘/租借站損壞',
    'report_issue_broken_description': '報告有問題的雨傘或故障的租借站。',
    'report_issue_contact_support_button': '其他 / 聯絡客服',
    'report_issue_contact_support_description': '對於任何其他問題，或者如果您需要與人交談。',
    'report_issue_toast_auth_required_title': '需要登入',
    'report_issue_toast_auth_required_desc': '請登入以報告此類問題。',
    'report_issue_toast_no_active_rental_title': '沒有進行中的租借',
    'report_issue_toast_no_active_rental_desc': '此選項用於報告您目前正在租借的雨傘的問題。您沒有進行中的租借。',
    'report_issue_confirm_lost_stolen_title': '確認遺失/被盜報告',
    'report_issue_back_to_selection_button': '返回選擇',
    'report_issue_important_notice_title': '重要通知',
    'report_issue_confirm_lost_stolen_alert_desc': '報告雨傘遺失或被盜將結束您目前的租借。您的 HK$100 按金可能會被沒收。此操作無法透過應用程式撤銷。請確保雨傘確實遺失或被盜。如果您之後找到了它，請聯絡客服。',
    'report_issue_current_rental_label': '目前租借：',
    'report_issue_started_label': '開始時間：',
    'report_issue_yes_report_lost_stolen_button': '是的，報告遺失/被盜',
    'report_issue_toast_lost_stolen_title': '已報告雨傘遺失/被盜',
    'report_issue_toast_lost_stolen_desc': '您的租借已結束。我們已記錄此問題。您的按金可能會被沒收。如有疑問，請聯絡客服。',
    'report_issue_capture_media_title': '報告損壞物品',
    'report_issue_capture_media_desc': '請將您的相機對準損壞的雨傘或租借站。這有助於我們更快地識別和解決問題。（這是一個模擬 - 不會實際拍攝或儲存任何照片）。',
    'report_issue_initializing_camera': '正在啟動相機...',
    'report_issue_camera_error_title': '相機錯誤',
    'report_issue_camera_error_desc_generic': '無法存取相機。請檢查權限。',
    'report_issue_retry_camera_button': '重試相機',
    'report_issue_confirm_report_button': '確認報告',
    'report_issue_toast_multiple_broken_title': '今日多次損壞報告',
    'report_issue_toast_multiple_broken_desc': '感謝您的報告。我們發現您今天已提交 {count} 次損壞報告。您目前的租借（如有）已結束。如果情況不尋常或您需要進一步協助，請致電 {customerServiceNumber} 聯絡客服。',
    'report_issue_toast_broken_rented_title': '已報告租借的雨傘損壞',
    'report_issue_toast_broken_rented_desc': '謝謝。您的租借已結束，問題已記錄。感謝您幫助我們保持服務順暢運作！',
    'report_issue_toast_report_submitted_title': '報告已提交',
    'report_issue_toast_report_submitted_desc': '感謝您的報告！我們會調查此問題。',
    'report_issue_camera_permission_denied': '相機權限遭拒。請在您的瀏覽器設定中啟用相機存取權限，以使用媒體報告損壞的物品。',
    'report_issue_camera_not_found': '找不到相機。請確保相機已連接並啟用。',
    'report_issue_camera_in_use_or_error': '相機已被其他應用程式使用或發生硬體錯誤。',
    'report_issue_camera_api_unavailable': '您的瀏覽器或此頁面無法存取相機（例如，不是 HTTPS）。',
    'report_issue_contact_support_step_title': '聯絡客戶支援',
    'report_issue_need_assistance_title': '需要協助嗎？',
    'report_issue_need_assistance_desc': '對於緊急事項或未涵蓋的問題，請聯絡我們的客戶支援。',
    'report_issue_contact_info_text': '您可以透過電話 <strong class="text-primary">{customerServiceNumber}</strong> 聯絡我們。',
    'report_issue_call_customer_service_button': '致電客戶支援',

    // Admin Page
    'admin_page_title': '管理員面板 - U-Dry',
    'admin_page_description': '管理 U-Dry 租借站和營運。',
    'admin_verifying_access': '正在驗證權限...',
    'admin_access_denied_title': '權限不足',
    'admin_access_denied_desc': '您沒有權限瀏覽此頁面。此區域僅限管理員存取。',
    'admin_go_to_homepage_button': '前往主頁',
    'admin_panel_main_title': 'U-Dry 管理員面板',
    'admin_welcome_message': '歡迎，{userName}。管理您的 U-Dry 營運。',
    'admin_dashboard_overview_title': '儀表板概覽',
    'admin_dashboard_overview_desc': '快速查看營運數據及分析。',
    'admin_stat_total_stalls': '總租借站數量',
    'admin_stat_total_stalls_desc': '目前運作中',
    'admin_stat_total_umbrellas': '總雨傘數量',
    'admin_stat_total_umbrellas_desc': '所有租借站合計',
    'admin_stat_issues_reported': '已報告問題',
    'admin_stat_issues_reported_desc': '完整追蹤為未來功能',
    'admin_stat_avg_weekly_transactions': '平均每週交易數 / 租借站',
    'admin_stat_avg_weekly_transactions_desc': '基準平均值 (預留位置)',
    'admin_stat_avg_weekly_revenue': '平均每週收入 / 租借站',
    'admin_stat_avg_weekly_revenue_desc': '基準平均值 (預留位置)',
    'admin_stat_total_active_rentals': '目前進行中租賃總數',
    'admin_stat_active_rentals_desc': '即時進行中的租借數量',
    'admin_stat_analytics_desc': '整合資料庫後將啟用分析功能',
    'admin_stat_total_borrowing': '總借出次數',
    'admin_stat_total_borrowing_desc': '自追蹤開始',
    'admin_stat_total_returns': '總歸還次數',
    'admin_stat_total_returns_desc': '自追蹤開始',
    'admin_stall_management_title': '租借站管理',
    'admin_stall_management_desc': '檢視、管理和控制各個雨傘租借站。',
    'admin_stall_availability_label': '可用數量：',
    'admin_stall_transactions_label': '交易數 (本週)：',
    'admin_stall_revenue_label': '收入 (本週)：',
    'admin_stall_edit_button': '編輯詳情',
    'admin_stall_unlock_button': '解鎖',
    'admin_stall_manage_features_soon': '更多租借站管理功能即將推出。',
    'admin_machine_reg_title': '機器註冊',
    'admin_machine_reg_desc': '將新的雨傘機加入系統。(預留位置)',
    'admin_machine_reg_placeholder_text': '新增機器、指定其 ID、位置和初始雨傘數量的介面將在此處。',
    'admin_machine_reg_add_button': '新增機器',
    'admin_stall_available_umbrellas_label': '可用雨傘數量:',
    
    // Profile Settings Page
    'profile_settings_page_title': '個人設定 - U-Dry',
    'profile_settings_page_description': '查看並更新您的個人資料。',
    'profile_settings_title': '個人設定',
    'profile_settings_description': '管理您的帳戶詳細資料和偏好設定。',
    'profile_settings_name_label': '名稱',
    'profile_settings_email_label': '電子郵件',
    'profile_settings_update_button': '更新個人資料',
    'profile_settings_update_success': '個人資料更新成功！',
    'profile_settings_update_error': '個人資料更新失敗。',
    'profile_settings_loading': '正在載入個人資料...',
    'profile_settings_login_required': '您需要登入才能查看個人設定。',
    
    // Change Password Section (within Profile Settings)
    'change_password_title': '更改密碼',
    'change_password_description': '更新您的帳戶密碼。',
    'current_password_label': '目前密碼',
    'new_password_label': '新密碼',
    'confirm_new_password_label': '確認新密碼',
    'profile_settings_change_password_button': '更改密碼',
    'toast_password_change_success_title': '密碼已更改',
    'toast_password_change_success_desc': '您的密碼已成功更新。',
    'toast_password_change_error_title': '更改密碼失敗',
    'toast_password_change_error_desc': '無法更改密碼。請確保您目前的密碼正確無誤，然後再試一次。',
    'toast_password_mismatch': "新密碼不符。",
    'toast_reauth_required': "為安全起見，請先重新登入再更改密碼。",
    
    // Terms and Conditions Page
    'terms_page_title': '服務條款 - U-Dry',
    'terms_page_description': '閱讀使用 U-Dry 服務的服務條款。',
    'terms_content_title': '服務條款',
    'terms_last_updated': '最後更新日期：',
    'terms_section_1_title': '引言',
    'terms_section_1_content': "歡迎使用 U-Dry！本服務條款概述了使用 U-Dry 應用程式和服務的規則和規定。存取此應用程式即表示您接受這些條款和條件。如果您不同意本頁面所述的所有條款和條件，請勿繼續使用 U-Dry。",
    'terms_section_2_title': '免責聲明及責任限制',
    'terms_section_2_content_p1': "U-Dry 應用程式及其服務均以「現狀」和「現有」的基礎提供，不附帶任何明示或暗示的保證。我們不保證服務不會中斷、及時、安全或無錯誤。",
    'terms_section_2_content_p2': "在適用法律允許的最大範圍內，U-Dry 不對任何間接、附帶、特殊、後果性或懲罰性損害，或任何利潤或收入損失（無論是直接或間接產生），或任何數據、使用、商譽或其他無形損失負責，該等損失源於 (a) 您存取或使用或無法存取或使用本服務；(b) 任何第三方在本服務上的任何行為或內容；(c) 從本服務獲得的任何內容；及 (d) 未經授權存取、使用或更改您的傳輸或內容。這包括但不限於因使用本應用程式或其服務而據稱遭受的任何身體、精神或金錢損失。",
    'terms_section_3_title': '數據使用和隱私',
    'terms_section_3_content': "使用 U-Dry 即表示您同意我們根據我們的隱私政策（將添加連結）收集和使用資訊。我們可能會收集與您使用本應用程式和服務相關的數據，例如租賃歷史、位置數據（經您同意）和設備資訊。這些數據可能用於改進我們的服務、提供客戶支援以及進行分析。我們致力於保護您的隱私並負責任地處理您的數據。",
    'terms_section_4_title': '用戶責任',
    'terms_section_4_content': "您有責任維護您的帳戶和密碼的機密性，並限制對您設備的存取。您同意對在您的帳戶或密碼下發生的所有活動承擔責任。您有責任按時歸還租借的雨傘，並根據應用程式的指引報告任何損壞或遺失。濫用服務或雨傘可能導致帳戶暫停或終止，以及從您的可用餘額中扣除等同於按金的罰款。",
    'terms_section_5_title': '管轄法律',
    'terms_section_5_content': "本條款應受香港特別行政區法律管轄並依其解釋，不考慮其法律衝突規定。",
    'terms_section_6_title': '條款變更',
    'terms_section_6_content': "我們保留自行決定隨時修改或替換這些條款的權利。如果修訂是重大的，我們將在任何新條款生效前至少提前30天發出通知。何為重大變更將由我們自行決定。在任何修訂生效後繼續存取或使用我們的服務，即表示您同意受修訂條款的約束。",
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en'); 

  useEffect(() => {
    const savedLanguage = localStorage.getItem('udry-language') as Language | null;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'zh-HK')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('udry-language', lang); 
  }, []);

  const translate = useCallback((key: string, replacements: Record<string, string | number> = {}): string => {
    let translation = translations[language]?.[key] || translations['en']?.[key] || key;
    Object.keys(replacements).forEach(placeholder => {
      translation = translation.replace(new RegExp(`{${placeholder}}`, 'g'), String(replacements[placeholder]));
    });
    return translation;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
