// Generated by Capacitor
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "android"
include(":app")
include(":capacitor-android")
project(":capacitor-android").projectDir = file("./capacitor-android")
include(":capacitor-community-sqlite")
project(":capacitor-community-sqlite").projectDir = file("./capacitor-community-sqlite")
